name: default

on: [push, workflow_dispatch]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
      CC_TEST_REPORTER_ID: eae2fa40ae9e3d34015331647b26e69813f4a5fa5ccd7657147166508f4db8f3
    steps:
      - { uses: actions/checkout@v2, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v2, with: { node-version: 16, cache: 'yarn' } }

      - name: deps
        run: yarn --frozen-lockfile

      - name: build
        run: yarn build

      - name: test
        run: |
          curl -s -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          yarn test-ci
          ./cc-test-reporter after-build -t lcov

      - uses: actions/upload-artifact@v2
        with: { name: 'unit.xml', path: 'tmp/jest/unit.xml' }
      - uses: actions/upload-artifact@v2
        with: { name: 'coverage-unit', path: 'coverage/lcov-report' }
